org: llorent
service: api-web-scraping-sismos-igp

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::231672913990:role/LabRole

functions:
  scrape_sismos:
    handler: scraping_sismos.lambda_handler  
    package:
      include:
        - ./**  # Incluir todo el contenido del directorio
    events:
      - http:
          path: /scrape/sismos
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaSismosIGP:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismosIGP 
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
